Workaround for Ruby 4.0+
ref. https://github.com/banister/binding_of_caller/pull/90

```
An error occurred while loading ./spec/rspec/parameterized/table_syntax_spec.rb.
Failure/Error: where_binding = binding.of_caller(1)          # get where block binding

NoMethodError:
  undefined method 'of_caller' for an instance of Binding
 # ./lib/rspec/parameterized/table_syntax/table_syntax_implement.rb:6:in '|'
 # ./spec/rspec/parameterized/table_syntax_spec.rb:6:in 'block (3 levels) in <top (required)>'
 # ./vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'BasicObject#instance_eval'
 # ./vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'RSpec::Parameterized::Core::ExampleGroupMethods#define_cases'
 # ./vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:84:in 'RSpec::Parameterized::Core::ExampleGroupMethods#with_them'
 # ./spec/rspec/parameterized/table_syntax_spec.rb:11:in 'block (2 levels) in <top (required)>'
 # ./spec/rspec/parameterized/table_syntax_spec.rb:2:in 'block in <top (required)>'
 # ./spec/rspec/parameterized/table_syntax_spec.rb:1:in '<top (required)>'
```

https://github.com/rspec-parameterized/rspec-parameterized-table_syntax/actions/runs/20537642316/job/58997935169?pr=21